# Generated by Django 2.2.6 on 2019-11-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szkolenia', '0003_auto_20191122_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uczestnicy',
            name='telefon',
            field=models.CharField(max_length=9),
        ),
    ]
