# Generated by Django 2.2.6 on 2019-11-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szkolenia', '0004_auto_20191122_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizatorzy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('telefon', models.CharField(max_length=9)),
            ],
        ),
    ]
