# Generated by Django 2.2.6 on 2019-11-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szkolenia', '0006_szkolenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='UczestnicySzkolen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSzkolenia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szkolenia.Szkolenia')),
                ('idUczestnika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szkolenia.Uczestnicy')),
            ],
        ),
    ]
