# Generated by Django 2.2.6 on 2019-11-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szkolenia', '0007_uczestnicyszkolen'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizatorzy',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='uczestnicy',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
    ]
