# Generated by Django 2.0.13 on 2019-12-12 09:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('szkolenia', '0008_auto_20191128_1018'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='szkolenia',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='uczestnicyszkolen',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='szkolenia',
            name='opic',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uczestnicy',
            name='imie',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='uczestnicy',
            name='nazwisko',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='uczestnicy',
            name='telefon',
            field=models.CharField(default='', max_length=9),
        ),
    ]
