# Generated by Django 2.0.13 on 2020-01-16 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szkolenia', '0010_auto_20200109_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizatorzy',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
